spring:
   h2:
      console:
         enabled: true
   properties:
      format_sql: true
      show_sql: true
   hibernate: 
      ddl-auto: update
     
   mvc:
    view:
      prefix: /view/
      suffix: .jsp    
   datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    url: jdbc:h2:~/test
    
server:
  port: 8082
  